import torch

USE_GPU = torch.cuda.is_available()
SEQ_MAX_LEN = 250
DATA_SET = 'tiny_data' # 'people_daily_1998'
LABEL_FORMAT = 'bio'

EPOCH_NUM = 50
BATCH_SIZE = 20
EVAL_BATCH_INTERVAL = 10
EVAL_SIZE = 100

LEARNING_RATE = 0.1
MOMENTUM = 0
WEIGHT_DECAY = 1e-8

BERT_TRAINABLE = True
BERT_LAYER_INDEX = 11 # -1, 0 ~ 11
BERT_FULL_CONN_DROP_OUT = 0.5
BERT_LEARNING_RATE = 1e-5
BERT_WEIGHT_DECAY = 0
BERT_FULL_CONN_LEARNING_RATE = 0.003
BERT_FULL_CONN_WEIGHT_DECAY = 0.01